# 项目相关配置
huayi:
  # 名称
  name: HuaYi-Scrm
  # 版本
  version: 3.2.0
  # 版权年份
  copyrightYear: 2020
  # 文件上传路径
  profile: /Users/shiaihua/tmp/
  # 获取ip地址开关
  addressEnabled: true



# 开发环境配置
server:
  # 服务端口
  port: 8881
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
# 日志配置
logging:
  level:
    com.huayi: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug


# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
dubbo:
  application:
    id: scrm-service
    name: scrm-service
  server: true
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    id: dubbo
    name: dubbo
    port: -1
    status: server
  scan:
    basePackages: com.huayi.service.impl


# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.huayi
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mapper/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
